name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # Adjust branch as needed
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --build-arg ARGS="${{ secrets.ARGS }}" -t print-args-env .

      - name: Run Container and Save Output
        run: |
          docker run --rm --name print-args-container print-args-env
          docker cp print-args-container:/app/output.txt output.txt || echo "Failed to copy output"

      - name: Upload Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: output.txt
